database_user = "${DB_ROOT_USER}"
region = "${AWS_REGION}"
rds_vpc_cidr = "${RDS_VPC_CIDR}"
rds_subnet1_az = "${RDS_SUBNET1_AZ}"
rds_subnet2_az = "${RDS_SUBNET2_AZ}"
rds_subnet3_az = "${RDS_SUBNET3_AZ}"