---
- name: Destroy Postgres RDS
  hosts: local
  tasks:
  - name: Read data
    import_role:
      name: read_data
  - name: Destroy Networking
    import_role:
      name: destroy_nw
  - name: Destroy RDS
    import_role:
      name: destroy_rds